services:
  postgres:
    image: ankane/pgvector
    container_name: pgvector
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: docrag
      POSTGRES_USER: docraguser
      POSTGRES_PASSWORD: master
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./server/init.sql:/docker-entrypoint-initdb.d/init.sql # Optional: run init script

  redis:
    image: redis:7.0-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  pgdata:
